//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeropos {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:/.PHONGPHAT/visual_studio/zeropos/src/database/main_database.db")]
        public string database_file {
            get {
                return ((string)(this["database_file"]));
            }
            set {
                this["database_file"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZEROPOS\'SHOP")]
        public string shop_name {
            get {
                return ((string)(this["shop_name"]));
            }
            set {
                this["shop_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11/13 บ้านหนองงิ้ว นางรอง นางรอง บุรีรัมย์ 31110")]
        public string shop_address {
            get {
                return ((string)(this["shop_address"]));
            }
            set {
                this["shop_address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234567891234")]
        public string tax_id {
            get {
                return ((string)(this["tax_id"]));
            }
            set {
                this["tax_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*เราได้บันทึกข้อมูลของคุณไว้แล้ว*ขอบคุณที่ใช้บริการ")]
        public string bill_footer {
            get {
                return ((string)(this["bill_footer"]));
            }
            set {
                this["bill_footer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string printer_name {
            get {
                return ((string)(this["printer_name"]));
            }
            set {
                this["printer_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool auto_bill_print {
            get {
                return ((bool)(this["auto_bill_print"]));
            }
            set {
                this["auto_bill_print"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float vat {
            get {
                return ((float)(this["vat"]));
            }
            set {
                this["vat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shop_phone {
            get {
                return ((string)(this["shop_phone"]));
            }
            set {
                this["shop_phone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZR")]
        public string bill_prefix {
            get {
                return ((string)(this["bill_prefix"]));
            }
            set {
                this["bill_prefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\.PHONGPHAT\\visual_studio\\zeropos\\src\\logo.png")]
        public string logo_path {
            get {
                return ((string)(this["logo_path"]));
            }
            set {
                this["logo_path"] = value;
            }
        }
    }
}
